apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: tasklist
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJVMHhOWVd0dmJXRjZhVHBuYUhCZlZXbFdSMWhPUkhZNWIyWmFjSGhrU1doUVpGcE5VbFpyVUVSblMyeHFNMFJFY21WRSJ9fX0=
